config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => "user_registrations"}
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]
  resources :products do
    resources :comments
  end
  
  resources :users
	root 'static_pages#index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
	has_many :comments
	validates :name, presence: true
	# validates :description, presence: true
	# validates :image_url, presence: true
	# validates :colour, presence: true
	# validates :price, presence: true
	def self.search(search_term)
		if Rails.env == "development"
			@products = Product.where("name LIKE ?", "%#{search_term}%")
		else
			@products = Product.where("name ilike ?", "%#{search_term}%")
		end
	end

	def highest_rating_comment
		comments.rating_desc.first
	end
	def lowest_rating_comment
		comments.rating_desc.last
	end
	def average_rating
		comments.average(:rating).to_f
	end
	def views
		$redis.get("product:#{id}") # get product id
	end
	def viewed!
		$redis.incr("product:#{id}") # increment product id
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    #return our filtered list here
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], per_page: 5)
    # @comments = Comment.paginate(:page =>params[:page], :per_page => 5)
    # @comments = Comment.paginate(:page => params[:page])
    @product.viewed!
  end
  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to :back, notice: 'Product created successfully!' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to '/products', notice: 'Product was successfully updated!' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed!' }
      format.json { head :no_content }
    end
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def cache_key_for_products
		count = @products
		max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"products/all=#{count}-#{max_updated_at}"
	end		 
end

app/views/products/_comments.html.erb
<div class="product-reviews">
	<% @comments.each do |comment| %>
		<%= render comment %>
	<% end %>
	<div class="apple_pagination">	
		<%= will_paginate @comments %>
	</div>
</div>

app/views/products/_form.html.erb
<!-- error handling -->
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- form -->
<form class="form-group">
<!-- <div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4"> -->
    <div class="form-group row">
      <%= f.label :name, class: "col-sm-2 col-form-label" %>
      <%= f.text_field(:name, class: "col-sm-8", placeholder: "Name") %>
    </div>

    <div class="form-group row">
      <%= f.label :description, class: "col-sm-2 col-form-label" %>
      <%= f.text_area(:description, class: "col-sm-8", placeholder: "Description") %>
    </div>

    <div class="form-group row">
      <%= f.label :image_url, class: "col-sm-2 col-form-label" %>
      <%= f.text_field(:image_url, class: "col-sm-8", placeholder: "Image Url") %>
    </div>

    <div class="form-group row">
      <%= f.label :colour, class: "col-sm-2 col-form-label" %>
      <%= f.text_field(:colour, class: "col-sm-8", placeholder: "Colour") %>
    </div>

    <div class="form-group row">
      <%= f.label :price, class: "col-sm-2 col-form-label" %>
      <%= f.text_field(:price, class: "col-sm-8", placeholder: "Price") %>
    </div>

    <div class="actions">
      <%= f.submit %><br><br>
      <!-- <#%= link_to 'Show', @product %> | -->
      <!-- <#%= link_to 'Back', products_path %> | -->
      <!-- <#%= link_to 'Edit', edit_product_path(product) %> -->
    </div>
  <% end %>
  <!-- </div>
</div> -->
</form>
  

app/views/products/_new_comment.html.erb
<% if signed_in? %>
	<h3>Add a review:</h3>
	<%= form_for([@product, @product.comments.build], remote: true) do |f| %>
		<div class="row">	
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label :body, "Comments" %><br>
					<%= f.text_area :body, class: "form-control" %>
					<div class="rating"></div><br>
					<div><%= f.submit "Submit" %></div>
				</div>	
			</div>			
		</div>
	<% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
	<div class="col-md-6">
		 <h4><%= product.name %></h4>
	   <%= link_to image_tag(product.image_url, class: "img-responsive"), product %>
	   <br>
	   <span class="price img-responsive"><%= number_to_currency(product.price, unit: "CHF ", separator: ",") %></span>
	</div>
<% end %>

app/views/products/edit.html.erb
<h1 class="edit">Editing Product</h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<!-- <p id="notice"><#%= notice %></p> -->

<h1 class="products">Products</h1>
<h2 class="showcase"><%= link_to('View Our Showcase', static_pages_landing_page_path, id: "showcase")%></h2>
<div class="container-fluid">
  <div class="row">
  <!-- <#% cache @products do %> -->
  <% cache(cache_key_for_products) do %>
   <%= render @products %>
  <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1 class="new">New Product</h1>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<div class="container">
	<br><br>
		<h1><%= @product.name %></h1>
		<br>
		<div class="row data-product-id=<%= @product.id %>">		
			<div class="col-sm-4 col-md-6">
				<div class="product-show">			
				<% if signed_in? && current_user.admin? %>
					<%= link_to 'Edit', edit_product_path(@product) %> |
					<%= link_to 'Back', products_path %>
				<% else %>
				<% end %>
				<%= image_tag(@product.image_url, width:"350", class: "img-show img-zoom data_zoom_image:'@product.image_url'") %>
				<p><%= render partial: 'products/new_comment' %></p>
				</div>
			</div>
			<div class="col-sm-4 col-md-6">
				<br><br>			
				<div class="price price-show"> Our Price: <%= number_to_currency(@product.price, unit: "CHF ", separator: ",") %>
				</div>	
				<br>		
				<div class="rated" id=average-rating data-score="<%= @product.average_rating %>">Average Rating: </br>
				</div>
				<br>
				<% if signed_in? %>
				<div class= "paybtn-stripe">
					<%= form_tag "/payments/create" do %>
						<%= render partial: "shared/stripe_checkout_button" %>
						<%= hidden_field_tag(:product_id, @product.id) %>
					<% end %>
				</div>
				<br>
				<% end %>
				<div class="description">
				<%= @product.description %>
				</div>
			</div>
		</div>	
	<div class="row">
		<div class="col-sm-4 col-md-6">
			Product Views:
			<span class="badge">
				<%= @product.views %>
			</span>			
		</div>
		<div class="col-sm-4 col-md-6">
		</div>
	</div>
	<br>
	<div class="alert alert-info" style="display:none" role="alert">
		A new comment was posted!
	</div>
	<div class='product-reviews'><%= render partial: 'products/comments' %></div>
	<div><% @product.highest_rating_comment %></div>			
</div>