config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => "user_registrations"}
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]
  resources :products do
    resources :comments
  end
  
  resources :users
	root 'static_pages#index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social Dance Products</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="site" data-spy="scroll" data-target=".navbar">
    <!-- begin navbar  -->
  	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed btn btn-default btn-xs" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-form navbar-left search" role="search">
            <div class="form-group-sm">
              <%= form_tag("/products", method: "get") do %>
                <%= label_tag(:q, ('<span class="glyphicon glyphicon-search"></span>').html_safe, class: 'search_label') %>
                <%= text_field_tag(:q, nil, placeholder: 'Products', class: 'form-control-xs') %>
                <%= submit_tag("Check Products", data: {disable_with: "Working..."}, class: 'btn btn-default btn-xs') %>
              <% end %>
            </div> <!-- end form-group -->
          </div>
        </div> <!-- end navbar header -->
        <div class="navbar-collapse collapse navbar-right">
  		    <ul class="nav navbar-nav navbar-right">
           <li><%= link_to('Home', root_path) %></li>
           <li><%= link_to('Products', products_path) %></li>
  			   <li><%= link_to('About', static_pages_about_path) %></li>
  			   <li><%= link_to('Contact', static_pages_contact_path) %></li>
           <% if user_signed_in? %>
           <li><%= link_to('Account', users_path) %></li>
           <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
           <% else %>
           <li> <%= link_to('Login', new_user_session_path) %></li>
           <li><%= link_to('Sign Up', new_user_registration_path) %></li>
           <% end %>
  		    </ul>
        </div> <!-- end navbar-collapse -->
      </div> <!--end nav container-fluid -->
    </nav> <!-- end navbar -->
    <main class="site-content">
    <br><br>
    <div class="message">
      <% if notice %>
        <p id="notice" class="alert alert-success" role="alert"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p id="alert" class="alert alert-danger" role="alert"><%= alert %></p>
      <% end %>
    </div>

    <%= yield %>
    </main>
    <footer class="site-footer">
    	&copy; 2016-2022 Justin P. Dickerson
    </footer>
  </body>
</html>